### ISSUE TITLE
Code....

### ISSUE THREAD

**Issue by gamegam** [DarkWav/SAC-rewrite#12]
Can I have the sauce for AntiFly, AntiSpeed?

**Comment by DarkWav** [comment]
The current AntiSpeed that's found in the SAC-rewrite is licensed under the [MIT License](https://github.com/DarkWav/SAC-rewrite/blob/master/LICENSE), which means you can freely use the source code as long as you

* don't claim the used code as your own
* give proper credit to the [contributors](https://github.com/DarkWav/SAC-rewrite/graphs/contributors) and me
* acknowledge that the [contributors](https://github.com/DarkWav/SAC-rewrite/graphs/contributors) and me don't provide you with any kind of warranty
* acknowledge that none of the contributors nor me can be held liable for any damage the code may cause

That said, the relevant source code is in the following files:

* [Analyzer.php](https://github.com/DarkWav/SAC-rewrite/blob/master/src/DarkWav/SAC/Analyzer.php) - Look inside the `processPlayerMoveEvent()` function
* [SpeedCheck.php](https://github.com/DarkWav/SAC-rewrite/blob/master/src/DarkWav/SAC/checks/SpeedCheck.php) - Look inside the `run()` function

The AntiFly from the rewrite currently does nothing. You would have to use the AntiFly from SACv3. **Please note that code from SACv3 does not work with current versions of PocketMine-MP and you will have to adjust parts of the code.** SACv3 is also licensed under the [GNU General Public License 3](https://github.com/DarkWav/SAC/blob/master/LICENSE). This license, on top of the points mentioned above, also requires you to [open-source](https://en.wikipedia.org/wiki/Open_source) the plugin you use the AntiFly source code in. 
That said, the relevant source code is in the following file:

* [Observer.php](https://github.com/DarkWav/SAC/blob/master/src/DarkWav/SAC/Observer.php) - Look inside the `SACIsOnGround()`, `AllBlocksAir()`, `OnMove()` and `CheckSpeedFlyGlide()` functions.

**If you have any further questions, feel free to reply.**

**Comment by gamegam** [comment]
No, I'll leave a source.
